"""adding column author

Revision ID: 9041a1fdfe3c
Revises: e6b7934df7f7
Create Date: 2021-04-30 13:52:38.167743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9041a1fdfe3c'
down_revision = 'e6b7934df7f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('author', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'author')
    # ### end Alembic commands ###
